version: '3.3'

services:

  db:
    image: mysql
    restart: always
    volumes:
      - /opt/known/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=known
      - MYSQL_USER=known
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    networks:
      backend:

  app:
    image: egoexpress/known:0.9.9
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - /opt/known/uploads:/known/uploads
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - KNOWN_MYSQL_PASSWORD=
    networks:
      frontend:
      backend:

networks:
  frontend:
  backend:
