services:

  db:
    image: mariadb:11.6
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=known
      - MYSQL_USER=known
      - MYSQL_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD-unset}
      - MYSQL_ROOT_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD-unset}
    networks:
      backend:

  app:
    image: egoexpress/known:20241215
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - data:/known/uploads
    environment:
      - VIRTUAL_HOST=${DOCKER_KNOWN_HOSTNAME-unset}
      - LETSENCRYPT_HOST=${DOCKER_KNOWN_HOSTNAME-unset}
      - LETSENCRYPT_EMAIL=${DOCKER_LETSENCRYPT_EMAIL-unset}
      - KNOWN_MYSQL_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD-unset}
      - SSL_POLICY=Mozilla-Modern
    networks:
      frontend:
      backend:

networks:
  frontend:
  backend:
    internal: true

volumes:
  db:
  data:
