datavolume:
#  restart: on-failure:10
  image: debian:latest
  volumes:
    - /opt/known/mongodb:/var/lib/mongodb
    - /opt/known/uploads:/known/uploads

mongodb:
#  restart: on-failure:10
  image: mongo:latest
  volumes_from:
    - datavolume

known:
#  restart: on-failure:10
  image: egoexpress/known
  volumes_from:
    - datavolume
  ports:
    - "80:80"
  links:
    - "mongodb:mongodb"
