datavolume:
  container_name: known-data
  image: debian:latest
  restart: on-failure:10
  volumes:
    - /opt/known/mongodb:/var/lib/mongodb
    - /opt/known/uploads:/known/uploads

mongodb:
  container_name: known-mongodb
  image: mongo:latest
  restart: on-failure:10
  volumes_from:
    - datavolume

known:
  container_name: known
  image: egoexpress/known:latest
  restart: on-failure:10
  volumes_from:
    - datavolume
  ports:
    - "80:80"
  links:
    - "mongodb:mongodb"
