datavolume:
  container_name: known-data
  image: debian:latest
  restart: on-failure:10
  volumes:
    - /opt/known/mysql:/var/lib/mysql
    - /opt/known/uploads:/known/uploads

mysql:
  container_name: known-mysql
  image: mysql
  restart: on-failure:10
  volumes_from:
    - datavolume
  environment:
    - MYSQL_DATABASE=known
    - MYSQL_USER=known
    - MYSQL_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD}

known:
  container_name: known
  image: egoexpress/known:latest
  restart: on-failure:10
  volumes_from:
    - datavolume
  links:
    - "mysql:mysql"
  environment:
    - VIRTUAL_HOST=${DOCKER_KNOWN_HOSTNAME}
    - LETSENCRYPT_HOST=${DOCKER_KNOWN_HOSTNAME}
    - LETSENCRYPT_EMAIL=${DOCKER_LETSENCRYPT_EMAIL}
    - KNOWN_MYSQL_PASSWORD=${DOCKER_KNOWN_MYSQL_PASSWORD}
