datavolume:
#  restart: on-failure:10
  image: debian:latest
  volumes:
    - /opt/known/mysql:/var/lib/mysql
    - /opt/known/uploads:/known/uploads
#    - /opt/known/IdnoPlugins:/var/www/known/IdnoPlugins

mongodb:
#  restart: on-failure:10
  image: mongo:latest
  volumes_from:
    - datavolume

known:
#  restart: on-failure:10
  image: egoexpress/known
  volumes_from:
    - datavolume
  ports:
    - "80:80"
  links:
    - "mongodb:mongodb"
